export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
